### PR TITLE
Update index.js to support Angular 1.3.16 - 17

### PR DESCRIPTION
**Pull request by itsikavidan**
Added support to Angular v 1.3.16-17

### CODE REVIEW

**Comment by passy** [comment]
Thanks!

**Comment by itsikavidan** [comment]
no problem !

could you create a new tag for the commit ?

**Comment by shahata** [comment]
done last week. sorry, forgot to update here.

**Comment by passy** [comment]
Thanks! :)

**Comment by shahata** [comment]
@passy I've added you as collaborator on npm, so you can publish to if you like. I don't know why I didn't do it before :)

**Pull request merged**
